/* eslint-disable */
import {useState, useEffect} from 'react';
import Head from 'next/head';
import Header from '../components/Header';
import NavItems from '../components/NavItems';
import MovieList from '../components/MovieList';
import fetchMovies from '../features/fetchMovies';
import { useRouter } from 'next/router';
import useResults from '../hooks/useResults';

export default function Home({resultsData, dropdownOpen, setDropdownOpen, onDropdownToggle}) {
  const { asPath } = useRouter();
  const searchTerm = asPath?.split('=')[1]?.split('-').join(' ');
  const { movieResults, loading } = useResults();
  const fetchedData = JSON.parse(resultsData);

  return (
    <div onClick={onDropdownToggle} role="presentation">
      <Head>
        <title>Movies - {searchTerm || 'Trending'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header value={searchTerm} dropdownOpen={dropdownOpen} setDropdownOpen={setDropdownOpen} />
      <NavItems />
      <MovieList results={!searchTerm ? fetchedData?.results : movieResults} loading={loading} />
    </div>
  );
}

export async function getStaticProps() {
  const baseURL = 'https://api.themoviedb.org/3';
  const data = await fetch(`${baseURL}${fetchMovies.trendingMovies}`)
  const stylesheet = await data.text();

    return {
      props: {
        resultsData: stylesheet,
      },
    };
};


